"""
API endpoints for downloading documents generated by the ReAct agent.

Generated documents are stored temporarily in Redis (TTL 1h) after
being created by the generate_document tool. This router provides
the download endpoint.
"""

import json
import logging

import redis.asyncio as aioredis
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response

from app.core.config import settings
from app.core.security import verify_api_key_or_bearer

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/emma/generated", tags=["generated-documents"])

GENERATED_DOC_PREFIX = "emma:generated_doc:"


@router.get(
    "/{doc_id}/download",
    summary="Download a generated document",
    description="Download a DOCX document generated by the generate_document tool. "
    "Documents are available for 1 hour after generation.",
)
async def download_generated_document(
    doc_id: str,
    _: bool = Depends(verify_api_key_or_bearer),
) -> Response:
    """Download a generated DOCX document by its ID."""
    r = aioredis.from_url(settings.redis_url)

    try:
        # Get metadata for filename
        meta_raw = await r.get(f"{GENERATED_DOC_PREFIX}{doc_id}:meta")
        if not meta_raw:
            raise HTTPException(
                status_code=404,
                detail=f"Documento no encontrado o expirado: {doc_id}. "
                "Los documentos generados estan disponibles durante 1 hora.",
            )

        meta = json.loads(meta_raw)
        title = meta.get("title", "documento")

        # Get DOCX bytes
        docx_bytes = await r.get(f"{GENERATED_DOC_PREFIX}{doc_id}:bytes")
        if not docx_bytes:
            raise HTTPException(
                status_code=404,
                detail="Contenido del documento no encontrado (posiblemente expirado).",
            )

        # Sanitize filename
        safe_title = "".join(
            c if c.isalnum() or c in (" ", "-", "_") else "_"
            for c in title
        ).strip() or "documento"

        return Response(
            content=docx_bytes,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={
                "Content-Disposition": f'attachment; filename="{safe_title}.docx"',
            },
        )
    finally:
        await r.aclose()


@router.get(
    "/{doc_id}/info",
    summary="Get generated document metadata",
    description="Get metadata about a generated document without downloading it.",
)
async def get_generated_document_info(
    doc_id: str,
    _: bool = Depends(verify_api_key_or_bearer),
):
    """Get metadata for a generated document."""
    r = aioredis.from_url(settings.redis_url)

    try:
        meta_raw = await r.get(f"{GENERATED_DOC_PREFIX}{doc_id}:meta")
        if not meta_raw:
            raise HTTPException(
                status_code=404,
                detail=f"Documento no encontrado o expirado: {doc_id}.",
            )

        meta = json.loads(meta_raw)
        ttl = await r.ttl(f"{GENERATED_DOC_PREFIX}{doc_id}:bytes")

        return {
            "doc_id": doc_id,
            "title": meta.get("title", ""),
            "source_title": meta.get("source_title", ""),
            "source_document_id": meta.get("source_document_id", ""),
            "modifications": meta.get("modifications", ""),
            "size_bytes": meta.get("size_bytes", 0),
            "ttl_seconds": max(ttl, 0),
        }
    finally:
        await r.aclose()
