"""
API endpoints for generating and downloading knowledge report documents.

Reports are generated by the generate_knowledge_report tool and stored in
Redis. These endpoints allow converting stored reports to DOCX and downloading them.
"""

import json
import logging
from typing import Optional

import httpx
import redis.asyncio as aioredis
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel

from app.agents.langgraph.tools.document_generator import _render_document_docx
from app.core.config import settings
from app.core.security import verify_api_key_or_bearer

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/emma/reports", tags=["reports"])

REPORT_PREFIX = "emma:report:"
DOCX_TTL = 3600  # 1 hour


class GenerateDocumentRequest(BaseModel):
    mode: str = "new"  # "new" | "template"
    template_document_id: Optional[str] = None
    title: Optional[str] = None


@router.post(
    "/{report_id}/generate-document",
    summary="Generate a DOCX document from a stored report",
    description="Converts a knowledge report stored in Redis into a downloadable DOCX file. "
    "Mode 'new' creates a plain DOCX from the report text. "
    "Mode 'template' uses the document forge service to fill a template.",
)
async def generate_report_document(
    report_id: str,
    body: GenerateDocumentRequest,
    _: bool = Depends(verify_api_key_or_bearer),
):
    """Generate a DOCX from a stored knowledge report."""
    r = aioredis.from_url(settings.redis_url)

    try:
        # Fetch report metadata
        meta_raw = await r.get(f"{REPORT_PREFIX}{report_id}:meta")
        if not meta_raw:
            raise HTTPException(
                status_code=404,
                detail=f"Informe no encontrado o expirado: {report_id}. "
                "Los informes están disponibles durante 1 hora tras su generación.",
            )

        meta = json.loads(meta_raw)
        entity_label = meta.get("entity_label", "entidad")
        report_type = meta.get("report_type", "informe")

        # Determine title
        title = body.title or f"Informe {report_type.capitalize()} — {entity_label}"

        # Fetch report text
        report_text = await r.get(f"{REPORT_PREFIX}{report_id}:text")
        if not report_text:
            raise HTTPException(
                status_code=404,
                detail="Contenido del informe no encontrado (posiblemente expirado).",
            )

        if isinstance(report_text, bytes):
            report_text = report_text.decode("utf-8")

        docx_bytes: Optional[bytes] = None

        # Template mode: try forge service first, fall back to "new"
        if body.mode == "template" and body.template_document_id:
            docx_bytes = await _generate_via_forge(
                template_document_id=body.template_document_id,
                title=title,
                report_text=report_text,
            )
            if docx_bytes is None:
                logger.warning(
                    f"generate_report_document: forge fallback to 'new' mode for report {report_id}"
                )

        # "new" mode (or forge fallback)
        if docx_bytes is None:
            source_title = entity_label
            docx_bytes = _render_document_docx(title, report_text, source_title)

        # Store DOCX in Redis with TTL
        await r.setex(f"{REPORT_PREFIX}{report_id}:docx", DOCX_TTL, docx_bytes)

        download_url = f"/emma/reports/{report_id}/download"

        return {
            "download_url": download_url,
            "format": "docx",
            "size_bytes": len(docx_bytes),
            "title": title,
        }

    finally:
        await r.aclose()


async def _generate_via_forge(
    template_document_id: str,
    title: str,
    report_text: str,
) -> Optional[bytes]:
    """Call the document forge service to render a DOCX from a template.

    Returns DOCX bytes on success, or None if no fields were detected
    (caller should fall back to 'new' mode).
    """
    forge_url = settings.document_forge_service_url.rstrip("/")

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            # Step 1: Analyze template to discover fillable fields
            analyze_resp = await client.post(
                f"{forge_url}/analyze",
                json={
                    "document_id": template_document_id,
                    "user_intent": title,
                },
                headers={"X-API-Key": settings.MICROSERVICES_API_KEY},
            )
            analyze_resp.raise_for_status()
            analyze_data = analyze_resp.json()

            session_id = analyze_data.get("session_id")
            fields = analyze_data.get("fields", [])

            if not fields:
                logger.info(
                    "generate_report_document: forge template has no fields, falling back to 'new' mode"
                )
                return None

            # Build field values from report metadata + text
            field_values = {f.get("name", f"field_{i}"): report_text for i, f in enumerate(fields)}
            if fields:
                # Use the first field as the main content carrier
                first_field = fields[0].get("name")
                if first_field:
                    field_values = {first_field: report_text}

            # Step 2: Render the template with field values
            render_resp = await client.post(
                f"{forge_url}/render",
                json={
                    "session_id": session_id,
                    "field_values": field_values,
                    "output_formats": ["docx"],
                },
                headers={"X-API-Key": settings.MICROSERVICES_API_KEY},
            )
            render_resp.raise_for_status()
            render_data = render_resp.json()

            docx_download_url = (
                render_data.get("outputs", {}).get("docx", {}).get("download_url")
            )
            if not docx_download_url:
                logger.warning("generate_report_document: forge render returned no docx URL")
                return None

            # Step 3: Download the rendered DOCX
            download_resp = await client.get(
                f"{forge_url}{docx_download_url}",
                headers={"X-API-Key": settings.MICROSERVICES_API_KEY},
            )
            download_resp.raise_for_status()
            return download_resp.content

    except httpx.HTTPStatusError as e:
        logger.warning(
            f"generate_report_document: forge service HTTP error {e.response.status_code}: {e}"
        )
        return None
    except Exception as e:
        logger.warning(f"generate_report_document: forge service error: {e}")
        return None


@router.get(
    "/{report_id}/download",
    summary="Download a generated report DOCX",
    description="Download the DOCX document previously generated for a knowledge report. "
    "Call POST /generate-document first to create the DOCX.",
)
async def download_report_document(
    report_id: str,
    _: bool = Depends(verify_api_key_or_bearer),
) -> Response:
    """Download a generated DOCX for a knowledge report."""
    r = aioredis.from_url(settings.redis_url)

    try:
        # Fetch DOCX bytes
        docx_bytes = await r.get(f"{REPORT_PREFIX}{report_id}:docx")
        if not docx_bytes:
            raise HTTPException(
                status_code=404,
                detail=f"DOCX no encontrado para el informe {report_id}. "
                "Llama primero a POST /generate-document para generar el archivo.",
            )

        # Fetch metadata for filename
        meta_raw = await r.get(f"{REPORT_PREFIX}{report_id}:meta")
        entity_label = "informe"
        if meta_raw:
            meta = json.loads(meta_raw)
            entity_label = meta.get("entity_label", "informe")

        # Sanitize filename
        safe_label = "".join(
            c if c.isalnum() or c in (" ", "-", "_") else "_"
            for c in entity_label
        ).strip() or "informe"

        filename = f"informe_{safe_label}.docx"

        return Response(
            content=docx_bytes,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
            },
        )

    finally:
        await r.aclose()
