/**
 * Heartbeat Service for Emma On-Premise
 *
 * Fetches proactive insights generated by Emma's heartbeat system
 * and allows users to dismiss or mark them as acted upon.
 */

import { apiClient } from '@/lib/api-client'

// ─── Types ────────────────────────────────────────────────────────────────────

export type InsightUrgency = 'critical' | 'high' | 'medium' | 'low'

export type InsightStatus = 'pending' | 'delivered' | 'dismissed' | 'expired' | 'acted_on'

export interface SuggestedAction {
  action: string
  action_url: string | null
  priority: number
}

export interface ProactiveInsight {
  id: string
  tenant_id: string
  insight_type: string
  title: string
  summary: string
  details: string | null
  priority_score: number
  urgency: InsightUrgency
  confidence: number
  related_documents: string[]
  suggested_actions: SuggestedAction[]
  reasoning: string | null
  status: InsightStatus
  delivered_at: string | null
  dismissed_at: string | null
  acted_on_at: string | null
  created_at: string
  expires_at: string | null
}

export interface InsightListResponse {
  insights: ProactiveInsight[]
  total: number
  page: number
  page_size: number
  has_more: boolean
}

// ─── Service ──────────────────────────────────────────────────────────────────

class HeartbeatService {
  /**
   * List proactive insights with optional filtering.
   */
  async getInsights(params?: {
    status?: string
    insight_type?: string
    limit?: number
  }): Promise<{ data: InsightListResponse | null; error: string | null }> {
    try {
      const searchParams = new URLSearchParams()
      if (params?.status) searchParams.append('status', params.status)
      if (params?.insight_type) searchParams.append('insight_type', params.insight_type)
      if (params?.limit) searchParams.append('limit', params.limit.toString())

      const response = await apiClient.get<InsightListResponse>(
        `/emma/heartbeat/insights?${searchParams.toString()}`
      )
      if (response.error) {
        return { data: null, error: response.error }
      }
      return { data: response.data, error: null }
    } catch (error) {
      console.error('[HeartbeatService] getInsights error:', error)
      return { data: null, error: 'Error al obtener alertas' }
    }
  }

  /**
   * Dismiss an insight (user no longer wants to see it).
   */
  async dismissInsight(insightId: string): Promise<{ error: string | null }> {
    try {
      const response = await apiClient.post(`/emma/heartbeat/insights/${insightId}/dismiss`)
      if (response.error) {
        return { error: response.error }
      }
      return { error: null }
    } catch (error) {
      console.error('[HeartbeatService] dismissInsight error:', error)
      return { error: 'Error al descartar alerta' }
    }
  }

  /**
   * Mark an insight as acted upon.
   */
  async markAsActed(insightId: string): Promise<{ error: string | null }> {
    try {
      const response = await apiClient.post(`/emma/heartbeat/insights/${insightId}/acted`)
      if (response.error) {
        return { error: response.error }
      }
      return { error: null }
    } catch (error) {
      console.error('[HeartbeatService] markAsActed error:', error)
      return { error: 'Error al marcar alerta como resuelta' }
    }
  }
}

export const heartbeatService = new HeartbeatService()
