"""
Pydantic schemas for Agent Self-Verifies pattern.

This module defines the data structures for verified document generation,
where each claim is validated against Weaviate before being accepted.

Architecture:
    Writer Agent → Celery Verifier → Redis Cache → Document Assembly
    (Generate)      (Validate)        (Store)       (Output)
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
import uuid


class VerificationStatus(str, Enum):
    """Status of a claim verification."""
    PENDING = "pending"
    VERIFIED = "verified"
    REJECTED = "rejected"
    CORRECTED = "corrected"
    TIMEOUT = "timeout"
    ERROR = "error"


class VerificationEventType(str, Enum):
    """Types of events emitted during verified generation."""
    CLAIM_GENERATED = "claim_generated"
    VERIFICATION_STARTED = "verification_started"
    CLAIM_VERIFIED = "claim_verified"
    CLAIM_REJECTED = "claim_rejected"
    CLAIM_CORRECTED = "claim_corrected"
    VERIFICATION_TIMEOUT = "verification_timeout"
    DOCUMENT_COMPLETE = "document_complete"
    ERROR = "error"
    PROGRESS = "progress"


class CandidateClaim(BaseModel):
    """
    A claim generated by the Writer Agent, pending verification.

    This represents raw output from the LLM that needs to be validated
    against the source documents in Weaviate before acceptance.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    text: str = Field(..., description="The claim text to verify")
    source_query: str = Field(..., description="The original user query that prompted this claim")
    generation_order: int = Field(..., description="Order in which this claim was generated (1-indexed)")
    context_document_ids: List[str] = Field(
        default_factory=list,
        description="Document IDs used as context for generation"
    )
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        json_schema_extra = {
            "example": {
                "id": "claim-abc123",
                "text": "El contrato establece una cláusula de penalización del 5% por incumplimiento.",
                "source_query": "Resume los puntos clave del contrato con ACME",
                "generation_order": 1,
                "context_document_ids": ["doc-123", "doc-456"],
            }
        }


class EvidenceMatch(BaseModel):
    """
    Evidence found in Weaviate that supports or contradicts a claim.
    """
    document_id: str = Field(..., description="ID of the source document")
    document_title: Optional[str] = Field(None, description="Title of the source document")
    chunk_id: Optional[str] = Field(None, description="Specific chunk ID if applicable")
    text_excerpt: str = Field(..., description="Relevant text excerpt from the document")
    similarity_score: float = Field(..., ge=0.0, le=1.0, description="Semantic similarity score")
    supports_claim: bool = Field(..., description="Whether this evidence supports the claim")

    class Config:
        json_schema_extra = {
            "example": {
                "document_id": "doc-123",
                "document_title": "Contrato ACME 2024",
                "chunk_id": "chunk-789",
                "text_excerpt": "Se establece una penalización del 5% del valor total...",
                "similarity_score": 0.89,
                "supports_claim": True
            }
        }


class VerificationResult(BaseModel):
    """
    Result of verifying a claim against Weaviate.

    This is returned by the Celery verification task after searching
    for evidence and evaluating whether the claim is supported.
    """
    claim_id: str = Field(..., description="ID of the verified claim")
    status: VerificationStatus = Field(..., description="Verification outcome")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence in the verification")
    evidence: List[EvidenceMatch] = Field(
        default_factory=list,
        description="Evidence found for/against the claim"
    )
    correction: Optional[str] = Field(
        None,
        description="Suggested correction if claim was rejected but correctable"
    )
    rejection_reason: Optional[str] = Field(
        None,
        description="Reason for rejection if applicable"
    )
    verification_time_ms: int = Field(..., description="Time taken to verify in milliseconds")
    verified_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "claim_id": "claim-abc123",
                "status": "verified",
                "confidence": 0.85,
                "evidence": [
                    {
                        "document_id": "doc-123",
                        "text_excerpt": "Penalización del 5%...",
                        "similarity_score": 0.89,
                        "supports_claim": True
                    }
                ],
                "verification_time_ms": 1250
            }
        }


class VerifiedClaim(BaseModel):
    """
    A claim that has been verified and accepted.

    This is stored in Redis as part of the verified context cache,
    providing the foundation for subsequent claim generation.
    """
    id: str = Field(..., description="Unique identifier for this verified claim")
    text: str = Field(..., description="The verified claim text")
    original_text: Optional[str] = Field(
        None,
        description="Original text if claim was corrected"
    )
    status: VerificationStatus = Field(..., description="Final verification status")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Verification confidence")
    evidence_document_ids: List[str] = Field(
        default_factory=list,
        description="IDs of documents that support this claim"
    )
    generation_order: int = Field(..., description="Order in final document")
    verified_at: datetime = Field(default_factory=datetime.utcnow)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for Redis storage."""
        return {
            "id": self.id,
            "text": self.text,
            "original_text": self.original_text,
            "status": self.status.value,
            "confidence": self.confidence,
            "evidence_document_ids": self.evidence_document_ids,
            "generation_order": self.generation_order,
            "verified_at": self.verified_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "VerifiedClaim":
        """Create from dictionary (Redis deserialization)."""
        return cls(
            id=data["id"],
            text=data["text"],
            original_text=data.get("original_text"),
            status=VerificationStatus(data["status"]),
            confidence=data["confidence"],
            evidence_document_ids=data.get("evidence_document_ids", []),
            generation_order=data["generation_order"],
            verified_at=datetime.fromisoformat(data["verified_at"]) if isinstance(data["verified_at"], str) else data["verified_at"],
        )


class VerificationEvent(BaseModel):
    """
    An event emitted during the verified generation process.

    Used for SSE streaming to provide real-time progress updates.
    """
    event_type: VerificationEventType
    claim_id: Optional[str] = None
    data: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    progress_percent: Optional[int] = Field(None, ge=0, le=100)

    def to_sse(self) -> str:
        """Format as Server-Sent Event."""
        import json
        payload = {
            "event_type": self.event_type.value,
            "claim_id": self.claim_id,
            "data": self.data,
            "timestamp": self.timestamp.isoformat(),
            "progress_percent": self.progress_percent,
        }
        return f"data: {json.dumps(payload)}\n\n"


# =============================================================================
# API Request/Response Schemas
# =============================================================================


class VerifiedDocumentRequest(BaseModel):
    """
    Request to generate a verified document.
    """
    query: str = Field(..., description="The generation query/prompt")
    tenant_id: str = Field(..., description="Tenant identifier for document isolation")
    session_id: Optional[str] = Field(
        default=None,
        description="Session ID for caching (auto-generated if not provided)"
    )
    user_id: Optional[str] = Field(None, description="User ID for audit")

    # Generation parameters
    max_claims: int = Field(
        default=20,
        ge=1,
        le=50,
        description="Maximum number of claims to generate"
    )
    claim_temperature: float = Field(
        default=0.3,
        ge=0.0,
        le=1.0,
        description="Temperature for claim generation (lower = more deterministic)"
    )

    # Verification parameters
    verification_timeout_seconds: int = Field(
        default=45,
        ge=10,
        le=120,
        description="Timeout per claim verification"
    )
    confidence_threshold: float = Field(
        default=0.7,
        ge=0.0,
        le=1.0,
        description="Minimum confidence to accept a claim"
    )
    auto_correct: bool = Field(
        default=True,
        description="Automatically accept suggested corrections"
    )
    max_correction_attempts: int = Field(
        default=2,
        ge=0,
        le=5,
        description="Max correction attempts per claim"
    )

    # Context parameters
    context_document_ids: List[str] = Field(
        default_factory=list,
        description="Specific indexed document IDs to use as context (Weaviate)"
    )
    uploaded_file_ids: List[str] = Field(
        default_factory=list,
        description="Uploaded (non-indexed) file IDs whose extracted text is used as context"
    )
    collections: List[str] = Field(
        default_factory=list,
        description="Weaviate collections to search for evidence"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "query": "Genera un resumen del contrato con ACME incluyendo obligaciones y fechas clave",
                "tenant_id": "tenant-123",
                "max_claims": 10,
                "confidence_threshold": 0.75,
                "context_document_ids": ["doc-abc", "doc-def"]
            }
        }


class VerifiedClaimSummary(BaseModel):
    """Summary of a verified claim for the response."""
    text: str
    confidence: float
    status: VerificationStatus
    evidence_count: int


class VerifiedDocumentResponse(BaseModel):
    """
    Response containing the verified document.
    """
    session_id: str = Field(..., description="Session ID for this generation")
    query: str = Field(..., description="Original query")

    # The verified document
    document_text: str = Field(..., description="The assembled verified document")
    claims: List[VerifiedClaimSummary] = Field(
        default_factory=list,
        description="Summary of verified claims"
    )

    # Statistics
    total_claims_generated: int = Field(..., description="Total claims attempted")
    claims_verified: int = Field(..., description="Claims that passed verification")
    claims_corrected: int = Field(..., description="Claims that were corrected")
    claims_rejected: int = Field(..., description="Claims that were rejected")
    average_confidence: float = Field(..., ge=0.0, le=1.0)

    # Performance
    execution_time_ms: int = Field(..., description="Total execution time")
    verification_time_ms: int = Field(..., description="Time spent on verification")

    # Metadata
    evidence_document_ids: List[str] = Field(
        default_factory=list,
        description="All documents used as evidence"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "session_id": "session-xyz789",
                "query": "Genera un resumen del contrato con ACME",
                "document_text": "## Resumen del Contrato ACME\n\n1. El contrato establece...",
                "claims": [
                    {"text": "El contrato tiene vigencia de 2 años", "confidence": 0.92, "status": "verified", "evidence_count": 2}
                ],
                "total_claims_generated": 12,
                "claims_verified": 10,
                "claims_corrected": 1,
                "claims_rejected": 1,
                "average_confidence": 0.87,
                "execution_time_ms": 45000,
                "verification_time_ms": 38000
            }
        }


class VerificationSessionStatus(BaseModel):
    """
    Status of an ongoing or completed verification session.
    """
    session_id: str
    tenant_id: str
    status: str  # "in_progress", "completed", "error"
    claims_processed: int
    claims_total: int
    current_claim: Optional[str] = None
    progress_percent: int
    started_at: datetime
    updated_at: datetime
    error_message: Optional[str] = None


class SessionClaimsResponse(BaseModel):
    """Response containing verified claims for a session."""
    session_id: str
    tenant_id: str
    claims: List[VerifiedClaim]
    total_claims: int
    cache_ttl_remaining_seconds: Optional[int] = None
