"""
Sequential Workflow - Ordered Agent Execution

Agents take turns in a fixed order. Each agent sees all previous
messages and builds on the work of previous agents.

Typical use case: Search -> Analyze -> Summarize pipeline

FRAMEWORK: Microsoft Agent Framework
Uses SequentialBuilder for ordered multi-agent orchestration.
"""

import logging
from typing import List, Any, AsyncIterator
from dataclasses import dataclass

from agent_framework import SequentialBuilder, ChatAgent

logger = logging.getLogger(__name__)


@dataclass
class WorkflowResult:
    """Result from a workflow execution."""
    answer: str
    messages: List[Any]
    agents_used: List[str]
    turns_taken: int
    completed: bool


class SequentialWorkflow:
    """
    Sequential workflow where agents process in fixed order.

    Uses SequentialBuilder from Agent Framework to have agents take
    turns in the specified order. Each agent sees all previous
    messages from the conversation.

    Example flow: SearchAgent -> AnalystAgent -> SummarizerAgent
    """

    def __init__(
        self,
        agents: List[ChatAgent],
        max_turns: int = 15,
        termination_text: str = "TASK_COMPLETE",
    ):
        """
        Initialize sequential workflow.

        Args:
            agents: List of ChatAgent instances in execution order
            max_turns: Maximum total turns before stopping
            termination_text: Text that signals task completion
        """
        self.agents = agents
        self.max_turns = max_turns
        self.termination_text = termination_text

        # Build the sequential workflow
        self.workflow = (
            SequentialBuilder()
            .participants(agents)
            .max_turns(max_turns)
            .termination_text(termination_text)
            .build()
        )

        logger.debug(
            f"Created SequentialWorkflow with {len(agents)} agents: "
            f"{[a.name for a in agents]}"
        )

    async def run(self, task: str) -> WorkflowResult:
        """
        Execute the workflow with the given task.

        Args:
            task: Task description including any required context

        Returns:
            WorkflowResult with the final answer and execution metadata
        """
        logger.info(f"Starting sequential workflow: task='{task[:50]}...'")

        try:
            messages = []
            agents_used = set()
            answer = ""

            async for event in self.workflow.run_stream(task):
                if hasattr(event, 'content'):
                    messages.append(event)
                    answer = event.content
                    if hasattr(event, 'source'):
                        agents_used.add(event.source)

            completed = self.termination_text in answer if answer else False

            return WorkflowResult(
                answer=answer,
                messages=messages,
                agents_used=list(agents_used),
                turns_taken=len(messages),
                completed=completed,
            )

        except Exception as e:
            logger.exception(f"Sequential workflow error: {e}")
            return WorkflowResult(
                answer=f"Error executing workflow: {e}",
                messages=[],
                agents_used=[],
                turns_taken=0,
                completed=False,
            )

    async def run_stream(self, task: str) -> AsyncIterator[Any]:
        """
        Execute workflow with streaming of messages.

        Yields messages as they are generated by each agent.

        Args:
            task: Task description

        Yields:
            Messages as they are produced
        """
        logger.info(f"Starting streaming sequential workflow")

        try:
            async for event in self.workflow.run_stream(task):
                yield event
        except Exception as e:
            logger.exception(f"Streaming error: {e}")
            yield {"error": str(e)}


def create_analysis_pipeline(
    chat_client: Any,
    max_turns: int = 15,
) -> SequentialWorkflow:
    """
    Create a pre-configured Search -> Analyze -> Summarize pipeline.

    This is the default sequential workflow for document analysis.
    The agents process in order:
    1. SearchAgent: Finds relevant documents
    2. AnalystAgent: Performs deep analysis
    3. SummarizerAgent: Creates executive summary

    Args:
        chat_client: Agent Framework chat client
        max_turns: Maximum workflow turns

    Returns:
        Configured SequentialWorkflow
    """
    from ..agents import (
        create_search_agent,
        create_analyst_agent,
        create_summarizer_agent,
    )

    search = create_search_agent(chat_client)
    analyst = create_analyst_agent(chat_client)
    summarizer = create_summarizer_agent(chat_client)

    return SequentialWorkflow(
        agents=[search, analyst, summarizer],
        max_turns=max_turns,
    )


def create_contract_review_pipeline(
    chat_client: Any,
    max_turns: int = 20,
) -> SequentialWorkflow:
    """
    Create a pipeline for contract review.

    Flow: Search -> Contract Analysis -> Compliance Check -> Summary

    Args:
        chat_client: Agent Framework chat client
        max_turns: Maximum turns

    Returns:
        Configured SequentialWorkflow for contract review
    """
    from ..agents import (
        create_search_agent,
        create_contract_agent,
        create_compliance_agent,
        create_summarizer_agent,
    )

    search = create_search_agent(chat_client)
    contract = create_contract_agent(chat_client)
    compliance = create_compliance_agent(chat_client)
    summarizer = create_summarizer_agent(chat_client)

    return SequentialWorkflow(
        agents=[search, contract, compliance, summarizer],
        max_turns=max_turns,
    )
