"""initial nouxcube schema

Revision ID: 125fb6c09803
Revises: 
Create Date: 2026-04-08 19:33:03.255372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '125fb6c09803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('DOCUMENT_ANALYZER', 'CONTRACT_INTELLIGENCE', 'COMPLIANCE_CHECKER', 'SIGNATURE_AGENT', 'FINANCIAL_ANALYZER', 'LEGAL_ADVISOR', 'RAG_ASSISTANT', name='agenttype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_mode', sa.Enum('AUTOMATIC', 'CONFIRMATION_REQUIRED', 'SCHEDULED', name='agentexecutionmode'), nullable=True),
    sa.Column('requires_context', sa.Boolean(), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_type')
    )
    op.create_table('document_acl_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('acl_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('grantee_type', sa.String(length=20), nullable=False),
    sa.Column('grantee_id', sa.UUID(), nullable=True),
    sa.Column('permissions_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permissions_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_acl_audits_document_action', 'document_acl_audits', ['document_id', 'action'], unique=False)
    op.create_index(op.f('ix_document_acl_audits_action'), 'document_acl_audits', ['action'], unique=False)
    op.create_index(op.f('ix_document_acl_audits_document_id'), 'document_acl_audits', ['document_id'], unique=False)
    op.create_table('document_type_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_signer_count', sa.Integer(), nullable=True),
    sa.Column('default_field_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_document_type_tenant_name')
    )
    op.create_table('edit_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_file_name', sa.String(), nullable=True),
    sa.Column('template_file_mime', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('google_doc_id', sa.String(), nullable=False),
    sa.Column('google_doc_url', sa.Text(), nullable=False),
    sa.Column('google_doc_edit_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('original_content_hash', sa.String(), nullable=True),
    sa.Column('final_content_hash', sa.String(), nullable=True),
    sa.Column('changes_detected', sa.Boolean(), nullable=True),
    sa.Column('content_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('cleanup_attempted', sa.Boolean(), nullable=True),
    sa.Column('cleanup_completed', sa.Boolean(), nullable=True),
    sa.Column('cleanup_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_doc_id', name='uq_edit_sessions_google_doc_id')
    )
    op.create_index(op.f('ix_edit_sessions_google_doc_id'), 'edit_sessions', ['google_doc_id'], unique=True)
    op.create_index(op.f('ix_edit_sessions_id'), 'edit_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_edit_sessions_template_id'), 'edit_sessions', ['template_id'], unique=False)
    op.create_index(op.f('ix_edit_sessions_user_id'), 'edit_sessions', ['user_id'], unique=False)
    op.create_table('signature_placement_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('field_configurations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('pattern_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', name='uq_tenant_provider')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tag_name_tenant')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('sso_external_id', sa.String(length=255), nullable=True),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_team_member', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_sso_external_id'), 'users', ['sso_external_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_table('agent_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_definition_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('enabled_by', sa.UUID(), nullable=True),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_name', sa.String(length=100), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_mode_override', sa.Enum('AUTOMATIC', 'CONFIRMATION_REQUIRED', 'SCHEDULED', name='agentexecutionmode'), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('allowed_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_executions_per_day', sa.Integer(), nullable=True),
    sa.Column('max_executions_per_user_per_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], ),
    sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('health_message', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_document_roles', postgresql.ARRAY(sa.String()), server_default='{EVERYONE}', nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_type', 'name', name='uq_connector_tenant_type_name')
    )
    op.create_index(op.f('ix_connectors_connector_type'), 'connectors', ['connector_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags_array', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indexed', sa.Integer(), nullable=False),
    sa.Column('indexing_error', sa.Text(), nullable=True),
    sa.Column('folder_path', sa.String(length=2000), nullable=True),
    sa.Column('auto_classified', sa.Boolean(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), server_default='{EVERYONE}', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_category', 'documents', ['category'], unique=False)
    op.create_index('idx_documents_creator_created', 'documents', ['created_by', 'created_at'], unique=False)
    op.create_index('idx_documents_indexed', 'documents', ['indexed'], unique=False)
    op.create_index('idx_documents_roles', 'documents', ['roles'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_table('emma_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emma_sessions_user_last_message', 'emma_sessions', ['user_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_emma_sessions_session_id'), 'emma_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_emma_sessions_user_id'), 'emma_sessions', ['user_id'], unique=False)
    op.create_table('folder_markers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_path', sa.String(length=2000), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path', name='uq_folder_marker_tenant_path')
    )
    op.create_table('google_drive_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_user_id', sa.String(), nullable=False),
    sa.Column('google_email', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_drive_tokens_id'), 'google_drive_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_google_drive_tokens_user_id'), 'google_drive_tokens', ['user_id'], unique=True)
    op.create_table('information_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('documents_indexed', sa.Integer(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channels_creator_visibility', 'information_channels', ['created_by', 'visibility'], unique=False)
    op.create_index('idx_channels_next_sync', 'information_channels', ['next_sync_at', 'is_active'], unique=False)
    op.create_index(op.f('ix_information_channels_channel_type'), 'information_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_information_channels_created_by'), 'information_channels', ['created_by'], unique=False)
    op.create_table('lgpd_deletion_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_records_deleted', sa.Integer(), nullable=True),
    sa.Column('anonymized_records', sa.Integer(), nullable=True),
    sa.Column('lgpd_article', sa.String(length=50), nullable=False),
    sa.Column('deletion_method', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lgpd_deletions_user_date', 'lgpd_deletion_audits', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_lgpd_deletion_audits_user_id'), 'lgpd_deletion_audits', ['user_id'], unique=False)
    op.create_table('notebooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('chat_count', sa.Integer(), nullable=False),
    sa.Column('audio_count', sa.Integer(), nullable=False),
    sa.Column('presentation_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notebooks_archived', 'notebooks', ['is_archived'], unique=False)
    op.create_index('idx_notebooks_user_activity', 'notebooks', ['user_id', 'last_activity_at'], unique=False)
    op.create_index(op.f('ix_notebooks_user_id'), 'notebooks', ['user_id'], unique=False)
    op.create_table('signature_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contact_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_signature_contact_tenant_email')
    )
    op.create_index('idx_signature_contacts_email', 'signature_contacts', ['email'], unique=False)
    op.create_index('idx_signature_contacts_name', 'signature_contacts', ['name'], unique=False)
    op.create_table('signature_provider_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['signature_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_audits_provider_action', 'signature_provider_audits', ['provider_id', 'action'], unique=False)
    op.create_index(op.f('ix_signature_provider_audits_action'), 'signature_provider_audits', ['action'], unique=False)
    op.create_index(op.f('ix_signature_provider_audits_provider_id'), 'signature_provider_audits', ['provider_id'], unique=False)
    op.create_table('signature_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_content', sa.LargeBinary(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('signature_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('success_url', sa.String(length=500), nullable=True),
    sa.Column('error_url', sa.String(length=500), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['signature_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_site_guest_tenant_email')
    )
    op.create_index('idx_site_guests_email', 'site_guests', ['email'], unique=False)
    op.create_table('user_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_learning_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('response_style', sa.String(length=50), nullable=False),
    sa.Column('expertise_level', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('preferred_document_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('total_document_views', sa.Integer(), nullable=False),
    sa.Column('avg_session_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('ranking_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frequent_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frequent_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_learning_profile')
    )
    op.create_index('idx_user_learning_profiles_user', 'user_learning_profiles', ['user_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('execution_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['configuration_id'], ['agent_configurations.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('credentials_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_user_id', sa.String(length=255), nullable=True),
    sa.Column('oauth_email', sa.String(length=255), nullable=True),
    sa.Column('oauth_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['information_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('channel_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('external_url', sa.String(length=2000), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('weaviate_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['information_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'external_id', name='uq_channel_document_external')
    )
    op.create_index('idx_channel_docs_hash', 'channel_documents', ['content_hash'], unique=False)
    op.create_index('idx_channel_docs_status', 'channel_documents', ['channel_id', 'status'], unique=False)
    op.create_index('idx_channel_docs_weaviate', 'channel_documents', ['weaviate_id'], unique=False)
    op.create_index(op.f('ix_channel_documents_channel_id'), 'channel_documents', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_documents_status'), 'channel_documents', ['status'], unique=False)
    op.create_table('channel_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_deleted', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['information_channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_logs_channel_started', 'channel_sync_logs', ['channel_id', 'started_at'], unique=False)
    op.create_index('idx_sync_logs_status', 'channel_sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_channel_sync_logs_channel_id'), 'channel_sync_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_sync_logs_status'), 'channel_sync_logs', ['status'], unique=False)
    op.create_table('connector_content_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('content_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aspects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('property_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('association_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type_semantics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('property_semantics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovery_method', sa.String(length=50), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ccm_connector', 'connector_content_models', ['connector_id'], unique=True)
    op.create_table('connector_indexing_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('mime_type_pattern', sa.String(length=100), nullable=True),
    sa.Column('chunking_type', sa.String(length=50), nullable=False),
    sa.Column('chunking_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extract_entities', sa.Boolean(), nullable=False),
    sa.Column('entity_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extract_to_knowledge_graph', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cis_connector', 'connector_indexing_strategies', ['connector_id'], unique=False)
    op.create_index('idx_cis_doc_type', 'connector_indexing_strategies', ['document_type'], unique=False)
    op.create_index('idx_cis_priority', 'connector_indexing_strategies', ['priority'], unique=False)
    op.create_table('data_learning_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('results_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dlj_connector', 'data_learning_jobs', ['connector_id'], unique=False)
    op.create_index('idx_dlj_created', 'data_learning_jobs', ['created_at'], unique=False)
    op.create_index('idx_dlj_job_type', 'data_learning_jobs', ['job_type'], unique=False)
    op.create_index('idx_dlj_status', 'data_learning_jobs', ['status'], unique=False)
    op.create_table('document_acls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('grantee_type', sa.String(length=20), nullable=False),
    sa.Column('grantee_id', sa.UUID(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'grantee_type', 'grantee_id', name='uq_document_acl_grantee')
    )
    op.create_index('idx_document_acls_document_view', 'document_acls', ['document_id', 'can_view'], unique=False)
    op.create_index(op.f('ix_document_acls_document_id'), 'document_acls', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_acls_expires_at'), 'document_acls', ['expires_at'], unique=False)
    op.create_index(op.f('ix_document_acls_grantee_id'), 'document_acls', ['grantee_id'], unique=False)
    op.create_table('document_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('detected_document_type', sa.String(length=100), nullable=True),
    sa.Column('detected_document_type_display', sa.String(length=200), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('plan_id', sa.String(length=100), nullable=True),
    sa.Column('plan_title', sa.String(length=500), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('annotated_pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('annotated_pdf_url', sa.String(length=2000), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_analyses_created', 'document_analyses', ['created_at'], unique=False)
    op.create_index('idx_document_analyses_document', 'document_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_analyses_document_id'), 'document_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_analyses_status'), 'document_analyses', ['status'], unique=False)
    op.create_table('document_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('idx_document_metrics_last_viewed', 'document_metrics', ['last_viewed_at'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('document_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('view_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_complete_view', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('scroll_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_views_doc_user', 'document_views', ['document_id', 'user_id'], unique=False)
    op.create_index('idx_document_views_user_date', 'document_views', ['user_id', 'viewed_at'], unique=False)
    op.create_table('knowledge_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_value', sa.Text(), nullable=False),
    sa.Column('entity_label', sa.String(length=500), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('acl_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acl_role_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acl_everyone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_entities_source_doc', 'knowledge_entities', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entities_domain'), 'knowledge_entities', ['domain'], unique=False)
    op.create_index(op.f('ix_knowledge_entities_entity_type'), 'knowledge_entities', ['entity_type'], unique=False)
    op.create_table('learned_folder_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('path_pattern', sa.String(length=1000), nullable=False),
    sa.Column('level_semantics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('example_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('learned_from_sample_size', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lfp_confidence', 'learned_folder_patterns', ['confidence'], unique=False)
    op.create_index('idx_lfp_connector', 'learned_folder_patterns', ['connector_id'], unique=False)
    op.create_table('learned_property_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('source_property', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('target_field', sa.String(length=100), nullable=False),
    sa.Column('search_weight', sa.Float(), nullable=False),
    sa.Column('include_in_embedding', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_facetable', sa.Boolean(), nullable=False),
    sa.Column('transformation', sa.String(length=50), nullable=True),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('learned_from_usage', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'source_property', 'source_type', name='uq_lpm_connector_source_type')
    )
    op.create_index('idx_lpm_connector', 'learned_property_mappings', ['connector_id'], unique=False)
    op.create_index('idx_lpm_source', 'learned_property_mappings', ['source_property'], unique=False)
    op.create_index('idx_lpm_target', 'learned_property_mappings', ['target_field'], unique=False)
    op.create_table('learned_relationship_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('source_relationship', sa.String(length=255), nullable=False),
    sa.Column('relationship_category', sa.String(length=50), nullable=False),
    sa.Column('kg_edge_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('include_in_retrieval', sa.Boolean(), nullable=False),
    sa.Column('expansion_depth', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('instance_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'source_relationship', name='uq_lrt_connector_source')
    )
    op.create_index('idx_lrt_connector', 'learned_relationship_types', ['connector_id'], unique=False)
    op.create_index('idx_lrt_kg_edge', 'learned_relationship_types', ['kg_edge_type'], unique=False)
    op.create_table('notebook_audios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('script', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_url', sa.String(length=1000), nullable=True),
    sa.Column('audio_format', sa.String(length=10), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notebook_audios_created', 'notebook_audios', ['created_at'], unique=False)
    op.create_index('idx_notebook_audios_notebook', 'notebook_audios', ['notebook_id'], unique=False)
    op.create_index('idx_notebook_audios_status', 'notebook_audios', ['status'], unique=False)
    op.create_index(op.f('ix_notebook_audios_notebook_id'), 'notebook_audios', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_notebook_audios_status'), 'notebook_audios', ['status'], unique=False)
    op.create_table('notebook_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notebook_chats_last_message', 'notebook_chats', ['last_message_at'], unique=False)
    op.create_index('idx_notebook_chats_notebook', 'notebook_chats', ['notebook_id'], unique=False)
    op.create_index('idx_notebook_chats_user', 'notebook_chats', ['user_id'], unique=False)
    op.create_index(op.f('ix_notebook_chats_notebook_id'), 'notebook_chats', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_notebook_chats_user_id'), 'notebook_chats', ['user_id'], unique=False)
    op.create_table('notebook_presentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pptx_url', sa.String(length=1000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('slide_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notebook_presentations_created', 'notebook_presentations', ['created_at'], unique=False)
    op.create_index('idx_notebook_presentations_notebook', 'notebook_presentations', ['notebook_id'], unique=False)
    op.create_index('idx_notebook_presentations_status', 'notebook_presentations', ['status'], unique=False)
    op.create_index(op.f('ix_notebook_presentations_notebook_id'), 'notebook_presentations', ['notebook_id'], unique=False)
    op.create_index(op.f('ix_notebook_presentations_status'), 'notebook_presentations', ['status'], unique=False)
    op.create_table('signature_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_field_placements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('signer_identifier', sa.String(length=100), nullable=True),
    sa.Column('x_position', sa.Float(), nullable=False),
    sa.Column('y_position', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('field_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_request_signers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('authentication_method', sa.String(length=20), nullable=True),
    sa.Column('success_url', sa.String(length=500), nullable=True),
    sa.Column('error_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('signing_url', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_guest_otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['site_guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_guest_otp_guest_expires', 'site_guest_otp', ['guest_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_site_guest_otp_guest_id'), 'site_guest_otp', ['guest_id'], unique=False)
    op.create_table('site_guest_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('folder_path', sa.String(length=2000), nullable=True),
    sa.Column('permission_type', sa.String(length=20), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(document_id IS NOT NULL AND folder_path IS NULL) OR (document_id IS NULL AND folder_path IS NOT NULL)', name='ck_site_guest_permission_target'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['site_guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'document_id', 'permission_type', name='uq_site_guest_doc_permission'),
    sa.UniqueConstraint('guest_id', 'folder_path', 'permission_type', name='uq_site_guest_folder_permission')
    )
    op.create_index('idx_site_guest_permissions_document', 'site_guest_permissions', ['document_id'], unique=False)
    op.create_index('idx_site_guest_permissions_guest', 'site_guest_permissions', ['guest_id'], unique=False)
    op.create_index(op.f('ix_site_guest_permissions_guest_id'), 'site_guest_permissions', ['guest_id'], unique=False)
    op.create_table('site_guest_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['site_guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_guest_sessions_active', 'site_guest_sessions', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_site_guest_sessions_guest', 'site_guest_sessions', ['guest_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_site_guest_sessions_guest_id'), 'site_guest_sessions', ['guest_id'], unique=False)
    op.create_index(op.f('ix_site_guest_sessions_session_token_hash'), 'site_guest_sessions', ['session_token_hash'], unique=True)
    op.create_table('site_guest_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permission_type', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['site_guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_guest_shares_guest', 'site_guest_shares', ['guest_id'], unique=False)
    op.create_index(op.f('ix_site_guest_shares_guest_id'), 'site_guest_shares', ['guest_id'], unique=False)
    op.create_table('user_connector_auths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'connector_id', name='uq_user_connector_auth')
    )
    op.create_index('idx_user_connector_auth_valid', 'user_connector_auths', ['user_id', 'is_valid'], unique=False)
    op.create_index(op.f('ix_user_connector_auths_connector_id'), 'user_connector_auths', ['connector_id'], unique=False)
    op.create_index(op.f('ix_user_connector_auths_user_id'), 'user_connector_auths', ['user_id'], unique=False)
    op.create_table('user_document_syncs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=True),
    sa.Column('include_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exclude_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('last_sync_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delta_token', sa.Text(), nullable=True),
    sa.Column('documents_total', sa.Integer(), nullable=True),
    sa.Column('documents_indexed', sa.Integer(), nullable=True),
    sa.Column('documents_failed', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'connector_id', name='uq_user_document_sync')
    )
    op.create_index('idx_user_doc_sync_next', 'user_document_syncs', ['next_sync_at'], unique=False)
    op.create_index('idx_user_doc_sync_status', 'user_document_syncs', ['status'], unique=False)
    op.create_index(op.f('ix_user_document_syncs_connector_id'), 'user_document_syncs', ['connector_id'], unique=False)
    op.create_index(op.f('ix_user_document_syncs_status'), 'user_document_syncs', ['status'], unique=False)
    op.create_index(op.f('ix_user_document_syncs_user_id'), 'user_document_syncs', ['user_id'], unique=False)
    op.create_table('user_interaction_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('intent_detected', sa.String(length=50), nullable=True),
    sa.Column('dwell_time_seconds', sa.Integer(), nullable=True),
    sa.Column('scroll_depth_percentage', sa.Float(), nullable=True),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results_shown', sa.Integer(), nullable=True),
    sa.Column('results_clicked', sa.Integer(), nullable=True),
    sa.Column('selected_document_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_interactions_session', 'user_interaction_history', ['session_id'], unique=False)
    op.create_index('idx_user_interactions_user_type', 'user_interaction_history', ['user_id', 'interaction_type'], unique=False)
    op.create_index(op.f('ix_user_interaction_history_interaction_type'), 'user_interaction_history', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_user_interaction_history_session_id'), 'user_interaction_history', ['session_id'], unique=False)
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indexed_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('external_path', sa.Text(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_tenant_public', sa.Boolean(), nullable=False),
    sa.Column('shared_with_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shared_with_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('weaviate_collection', sa.String(length=100), nullable=True),
    sa.Column('weaviate_id', sa.UUID(), nullable=True),
    sa.Column('indexing_status', sa.String(length=20), nullable=True),
    sa.Column('indexing_error', sa.Text(), nullable=True),
    sa.Column('indexing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('learned_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indexing_strategy_id', sa.UUID(), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cached_path', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String()), server_default='{EVERYONE}', nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['indexing_strategy_id'], ['connector_indexing_strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'external_id', name='uq_indexed_doc_connector_external')
    )
    op.create_index('idx_indexed_doc_owner', 'indexed_documents', ['owner_id'], unique=False)
    op.create_index('idx_indexed_doc_status', 'indexed_documents', ['indexing_status'], unique=False)
    op.create_index('idx_indexed_doc_weaviate', 'indexed_documents', ['weaviate_id'], unique=False)
    op.create_index('idx_indexed_documents_roles', 'indexed_documents', ['roles'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_indexed_documents_connector_id'), 'indexed_documents', ['connector_id'], unique=False)
    op.create_index(op.f('ix_indexed_documents_connector_type'), 'indexed_documents', ['connector_type'], unique=False)
    op.create_index(op.f('ix_indexed_documents_content_hash'), 'indexed_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_indexed_documents_indexing_strategy_id'), 'indexed_documents', ['indexing_strategy_id'], unique=False)
    op.create_index(op.f('ix_indexed_documents_owner_id'), 'indexed_documents', ['owner_id'], unique=False)
    op.create_table('knowledge_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('relationship_strength', sa.Float(), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_rels_source', 'knowledge_relationships', ['source_entity_id'], unique=False)
    op.create_index('idx_knowledge_rels_target', 'knowledge_relationships', ['target_entity_id'], unique=False)
    op.create_index('idx_knowledge_rels_type', 'knowledge_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_knowledge_relationships_relationship_type'), 'knowledge_relationships', ['relationship_type'], unique=False)
    op.create_table('site_guest_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('folder_path', sa.String(length=2000), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['site_guests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['site_guest_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_site_guest_access_logs_action', 'site_guest_access_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_site_guest_access_logs_document', 'site_guest_access_logs', ['document_id'], unique=False)
    op.create_index('idx_site_guest_access_logs_guest_created', 'site_guest_access_logs', ['guest_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_site_guest_access_logs_action'), 'site_guest_access_logs', ['action'], unique=False)
    op.create_index(op.f('ix_site_guest_access_logs_guest_id'), 'site_guest_access_logs', ['guest_id'], unique=False)
    op.create_table('site_guest_share_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['site_guest_shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_id', 'document_id', name='uq_site_guest_share_document')
    )
    op.create_index('idx_site_guest_share_documents_document', 'site_guest_share_documents', ['document_id'], unique=False)
    op.create_index('idx_site_guest_share_documents_share', 'site_guest_share_documents', ['share_id'], unique=False)
    op.create_table('notebook_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('indexed_document_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(document_id IS NOT NULL AND indexed_document_id IS NULL) OR (document_id IS NULL AND indexed_document_id IS NOT NULL)', name='ck_notebook_source_single_ref'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indexed_document_id'], ['indexed_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notebook_sources_notebook', 'notebook_sources', ['notebook_id'], unique=False)
    op.create_index('idx_notebook_sources_processed', 'notebook_sources', ['is_processed'], unique=False)
    op.create_index(op.f('ix_notebook_sources_document_id'), 'notebook_sources', ['document_id'], unique=False)
    op.create_index(op.f('ix_notebook_sources_indexed_document_id'), 'notebook_sources', ['indexed_document_id'], unique=False)
    op.create_index(op.f('ix_notebook_sources_notebook_id'), 'notebook_sources', ['notebook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebook_sources_notebook_id'), table_name='notebook_sources')
    op.drop_index(op.f('ix_notebook_sources_indexed_document_id'), table_name='notebook_sources')
    op.drop_index(op.f('ix_notebook_sources_document_id'), table_name='notebook_sources')
    op.drop_index('idx_notebook_sources_processed', table_name='notebook_sources')
    op.drop_index('idx_notebook_sources_notebook', table_name='notebook_sources')
    op.drop_table('notebook_sources')
    op.drop_index('idx_site_guest_share_documents_share', table_name='site_guest_share_documents')
    op.drop_index('idx_site_guest_share_documents_document', table_name='site_guest_share_documents')
    op.drop_table('site_guest_share_documents')
    op.drop_index(op.f('ix_site_guest_access_logs_guest_id'), table_name='site_guest_access_logs')
    op.drop_index(op.f('ix_site_guest_access_logs_action'), table_name='site_guest_access_logs')
    op.drop_index('idx_site_guest_access_logs_guest_created', table_name='site_guest_access_logs')
    op.drop_index('idx_site_guest_access_logs_document', table_name='site_guest_access_logs')
    op.drop_index('idx_site_guest_access_logs_action', table_name='site_guest_access_logs')
    op.drop_table('site_guest_access_logs')
    op.drop_index(op.f('ix_knowledge_relationships_relationship_type'), table_name='knowledge_relationships')
    op.drop_index('idx_knowledge_rels_type', table_name='knowledge_relationships')
    op.drop_index('idx_knowledge_rels_target', table_name='knowledge_relationships')
    op.drop_index('idx_knowledge_rels_source', table_name='knowledge_relationships')
    op.drop_table('knowledge_relationships')
    op.drop_index(op.f('ix_indexed_documents_owner_id'), table_name='indexed_documents')
    op.drop_index(op.f('ix_indexed_documents_indexing_strategy_id'), table_name='indexed_documents')
    op.drop_index(op.f('ix_indexed_documents_content_hash'), table_name='indexed_documents')
    op.drop_index(op.f('ix_indexed_documents_connector_type'), table_name='indexed_documents')
    op.drop_index(op.f('ix_indexed_documents_connector_id'), table_name='indexed_documents')
    op.drop_index('idx_indexed_documents_roles', table_name='indexed_documents', postgresql_using='gin')
    op.drop_index('idx_indexed_doc_weaviate', table_name='indexed_documents')
    op.drop_index('idx_indexed_doc_status', table_name='indexed_documents')
    op.drop_index('idx_indexed_doc_owner', table_name='indexed_documents')
    op.drop_table('indexed_documents')
    op.drop_table('agent_execution_logs')
    op.drop_index(op.f('ix_user_interaction_history_session_id'), table_name='user_interaction_history')
    op.drop_index(op.f('ix_user_interaction_history_interaction_type'), table_name='user_interaction_history')
    op.drop_index('idx_user_interactions_user_type', table_name='user_interaction_history')
    op.drop_index('idx_user_interactions_session', table_name='user_interaction_history')
    op.drop_table('user_interaction_history')
    op.drop_index(op.f('ix_user_document_syncs_user_id'), table_name='user_document_syncs')
    op.drop_index(op.f('ix_user_document_syncs_status'), table_name='user_document_syncs')
    op.drop_index(op.f('ix_user_document_syncs_connector_id'), table_name='user_document_syncs')
    op.drop_index('idx_user_doc_sync_status', table_name='user_document_syncs')
    op.drop_index('idx_user_doc_sync_next', table_name='user_document_syncs')
    op.drop_table('user_document_syncs')
    op.drop_index(op.f('ix_user_connector_auths_user_id'), table_name='user_connector_auths')
    op.drop_index(op.f('ix_user_connector_auths_connector_id'), table_name='user_connector_auths')
    op.drop_index('idx_user_connector_auth_valid', table_name='user_connector_auths')
    op.drop_table('user_connector_auths')
    op.drop_index(op.f('ix_site_guest_shares_guest_id'), table_name='site_guest_shares')
    op.drop_index('idx_site_guest_shares_guest', table_name='site_guest_shares')
    op.drop_table('site_guest_shares')
    op.drop_index(op.f('ix_site_guest_sessions_session_token_hash'), table_name='site_guest_sessions')
    op.drop_index(op.f('ix_site_guest_sessions_guest_id'), table_name='site_guest_sessions')
    op.drop_index('idx_site_guest_sessions_guest', table_name='site_guest_sessions')
    op.drop_index('idx_site_guest_sessions_active', table_name='site_guest_sessions')
    op.drop_table('site_guest_sessions')
    op.drop_index(op.f('ix_site_guest_permissions_guest_id'), table_name='site_guest_permissions')
    op.drop_index('idx_site_guest_permissions_guest', table_name='site_guest_permissions')
    op.drop_index('idx_site_guest_permissions_document', table_name='site_guest_permissions')
    op.drop_table('site_guest_permissions')
    op.drop_index(op.f('ix_site_guest_otp_guest_id'), table_name='site_guest_otp')
    op.drop_index('idx_site_guest_otp_guest_expires', table_name='site_guest_otp')
    op.drop_table('site_guest_otp')
    op.drop_table('signature_request_signers')
    op.drop_table('signature_field_placements')
    op.drop_table('signature_events')
    op.drop_index(op.f('ix_notebook_presentations_status'), table_name='notebook_presentations')
    op.drop_index(op.f('ix_notebook_presentations_notebook_id'), table_name='notebook_presentations')
    op.drop_index('idx_notebook_presentations_status', table_name='notebook_presentations')
    op.drop_index('idx_notebook_presentations_notebook', table_name='notebook_presentations')
    op.drop_index('idx_notebook_presentations_created', table_name='notebook_presentations')
    op.drop_table('notebook_presentations')
    op.drop_index(op.f('ix_notebook_chats_user_id'), table_name='notebook_chats')
    op.drop_index(op.f('ix_notebook_chats_notebook_id'), table_name='notebook_chats')
    op.drop_index('idx_notebook_chats_user', table_name='notebook_chats')
    op.drop_index('idx_notebook_chats_notebook', table_name='notebook_chats')
    op.drop_index('idx_notebook_chats_last_message', table_name='notebook_chats')
    op.drop_table('notebook_chats')
    op.drop_index(op.f('ix_notebook_audios_status'), table_name='notebook_audios')
    op.drop_index(op.f('ix_notebook_audios_notebook_id'), table_name='notebook_audios')
    op.drop_index('idx_notebook_audios_status', table_name='notebook_audios')
    op.drop_index('idx_notebook_audios_notebook', table_name='notebook_audios')
    op.drop_index('idx_notebook_audios_created', table_name='notebook_audios')
    op.drop_table('notebook_audios')
    op.drop_index('idx_lrt_kg_edge', table_name='learned_relationship_types')
    op.drop_index('idx_lrt_connector', table_name='learned_relationship_types')
    op.drop_table('learned_relationship_types')
    op.drop_index('idx_lpm_target', table_name='learned_property_mappings')
    op.drop_index('idx_lpm_source', table_name='learned_property_mappings')
    op.drop_index('idx_lpm_connector', table_name='learned_property_mappings')
    op.drop_table('learned_property_mappings')
    op.drop_index('idx_lfp_connector', table_name='learned_folder_patterns')
    op.drop_index('idx_lfp_confidence', table_name='learned_folder_patterns')
    op.drop_table('learned_folder_patterns')
    op.drop_index(op.f('ix_knowledge_entities_entity_type'), table_name='knowledge_entities')
    op.drop_index(op.f('ix_knowledge_entities_domain'), table_name='knowledge_entities')
    op.drop_index('idx_knowledge_entities_source_doc', table_name='knowledge_entities')
    op.drop_table('knowledge_entities')
    op.drop_index('idx_document_views_user_date', table_name='document_views')
    op.drop_index('idx_document_views_doc_user', table_name='document_views')
    op.drop_table('document_views')
    op.drop_table('document_tags')
    op.drop_index('idx_document_metrics_last_viewed', table_name='document_metrics')
    op.drop_table('document_metrics')
    op.drop_index(op.f('ix_document_analyses_status'), table_name='document_analyses')
    op.drop_index(op.f('ix_document_analyses_document_id'), table_name='document_analyses')
    op.drop_index('idx_document_analyses_document', table_name='document_analyses')
    op.drop_index('idx_document_analyses_created', table_name='document_analyses')
    op.drop_table('document_analyses')
    op.drop_index(op.f('ix_document_acls_grantee_id'), table_name='document_acls')
    op.drop_index(op.f('ix_document_acls_expires_at'), table_name='document_acls')
    op.drop_index(op.f('ix_document_acls_document_id'), table_name='document_acls')
    op.drop_index('idx_document_acls_document_view', table_name='document_acls')
    op.drop_table('document_acls')
    op.drop_index('idx_dlj_status', table_name='data_learning_jobs')
    op.drop_index('idx_dlj_job_type', table_name='data_learning_jobs')
    op.drop_index('idx_dlj_created', table_name='data_learning_jobs')
    op.drop_index('idx_dlj_connector', table_name='data_learning_jobs')
    op.drop_table('data_learning_jobs')
    op.drop_index('idx_cis_priority', table_name='connector_indexing_strategies')
    op.drop_index('idx_cis_doc_type', table_name='connector_indexing_strategies')
    op.drop_index('idx_cis_connector', table_name='connector_indexing_strategies')
    op.drop_table('connector_indexing_strategies')
    op.drop_index('idx_ccm_connector', table_name='connector_content_models')
    op.drop_table('connector_content_models')
    op.drop_index(op.f('ix_channel_sync_logs_status'), table_name='channel_sync_logs')
    op.drop_index(op.f('ix_channel_sync_logs_channel_id'), table_name='channel_sync_logs')
    op.drop_index('idx_sync_logs_status', table_name='channel_sync_logs')
    op.drop_index('idx_sync_logs_channel_started', table_name='channel_sync_logs')
    op.drop_table('channel_sync_logs')
    op.drop_index(op.f('ix_channel_documents_status'), table_name='channel_documents')
    op.drop_index(op.f('ix_channel_documents_channel_id'), table_name='channel_documents')
    op.drop_index('idx_channel_docs_weaviate', table_name='channel_documents')
    op.drop_index('idx_channel_docs_status', table_name='channel_documents')
    op.drop_index('idx_channel_docs_hash', table_name='channel_documents')
    op.drop_table('channel_documents')
    op.drop_table('channel_credentials')
    op.drop_table('agent_executions')
    op.drop_index('idx_user_learning_profiles_user', table_name='user_learning_profiles')
    op.drop_table('user_learning_profiles')
    op.drop_table('user_images')
    op.drop_index('idx_site_guests_email', table_name='site_guests')
    op.drop_table('site_guests')
    op.drop_table('signature_requests')
    op.drop_index(op.f('ix_signature_provider_audits_provider_id'), table_name='signature_provider_audits')
    op.drop_index(op.f('ix_signature_provider_audits_action'), table_name='signature_provider_audits')
    op.drop_index('idx_provider_audits_provider_action', table_name='signature_provider_audits')
    op.drop_table('signature_provider_audits')
    op.drop_index('idx_signature_contacts_name', table_name='signature_contacts')
    op.drop_index('idx_signature_contacts_email', table_name='signature_contacts')
    op.drop_table('signature_contacts')
    op.drop_index(op.f('ix_notebooks_user_id'), table_name='notebooks')
    op.drop_index('idx_notebooks_user_activity', table_name='notebooks')
    op.drop_index('idx_notebooks_archived', table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index(op.f('ix_lgpd_deletion_audits_user_id'), table_name='lgpd_deletion_audits')
    op.drop_index('idx_lgpd_deletions_user_date', table_name='lgpd_deletion_audits')
    op.drop_table('lgpd_deletion_audits')
    op.drop_index(op.f('ix_information_channels_created_by'), table_name='information_channels')
    op.drop_index(op.f('ix_information_channels_channel_type'), table_name='information_channels')
    op.drop_index('idx_channels_next_sync', table_name='information_channels')
    op.drop_index('idx_channels_creator_visibility', table_name='information_channels')
    op.drop_table('information_channels')
    op.drop_index(op.f('ix_google_drive_tokens_user_id'), table_name='google_drive_tokens')
    op.drop_index(op.f('ix_google_drive_tokens_id'), table_name='google_drive_tokens')
    op.drop_table('google_drive_tokens')
    op.drop_table('folder_markers')
    op.drop_index(op.f('ix_emma_sessions_user_id'), table_name='emma_sessions')
    op.drop_index(op.f('ix_emma_sessions_session_id'), table_name='emma_sessions')
    op.drop_index('idx_emma_sessions_user_last_message', table_name='emma_sessions')
    op.drop_table('emma_sessions')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.drop_index('idx_documents_roles', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_indexed', table_name='documents')
    op.drop_index('idx_documents_creator_created', table_name='documents')
    op.drop_index('idx_documents_category', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_connectors_connector_type'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_table('agent_configurations')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_sso_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_index('idx_users_email_active', table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('signature_providers')
    op.drop_table('signature_placement_patterns')
    op.drop_index(op.f('ix_edit_sessions_user_id'), table_name='edit_sessions')
    op.drop_index(op.f('ix_edit_sessions_template_id'), table_name='edit_sessions')
    op.drop_index(op.f('ix_edit_sessions_id'), table_name='edit_sessions')
    op.drop_index(op.f('ix_edit_sessions_google_doc_id'), table_name='edit_sessions')
    op.drop_table('edit_sessions')
    op.drop_table('document_type_classifications')
    op.drop_index(op.f('ix_document_acl_audits_document_id'), table_name='document_acl_audits')
    op.drop_index(op.f('ix_document_acl_audits_action'), table_name='document_acl_audits')
    op.drop_index('idx_acl_audits_document_action', table_name='document_acl_audits')
    op.drop_table('document_acl_audits')
    op.drop_table('agent_definitions')
    # ### end Alembic commands ###