"""add agent management tables

Revision ID: 60341decaf9a
Revises: 6f6ae23807be
Create Date: 2025-08-05 13:45:46.825875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60341decaf9a'
down_revision = '6f6ae23807be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types if they don't exist
    conn = op.get_bind()
    
    # Check if agenttype exists
    result = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'agenttype'"))
    if not result.fetchone():
        op.execute("CREATE TYPE agenttype AS ENUM ('document_analyzer', 'contract_intelligence', 'compliance_checker', 'signature_agent', 'financial_analyzer', 'legal_advisor', 'rag_assistant')")
    
    # Check if agentexecutionmode exists
    result = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'agentexecutionmode'"))
    if not result.fetchone():
        op.execute("CREATE TYPE agentexecutionmode AS ENUM ('automatic', 'confirmation_required', 'scheduled')")
    
    # Create agent_definitions table
    op.create_table('agent_definitions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('agent_type', sa.Enum('document_analyzer', 'contract_intelligence', 'compliance_checker', 'signature_agent', 'financial_analyzer', 'legal_advisor', 'rag_assistant', name='agenttype'), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('capabilities', sa.JSON(), nullable=True),
        sa.Column('required_permissions', sa.JSON(), nullable=True),
        sa.Column('execution_mode', sa.Enum('automatic', 'confirmation_required', 'scheduled', name='agentexecutionmode'), nullable=True),
        sa.Column('requires_context', sa.Boolean(), nullable=True),
        sa.Column('supports_streaming', sa.Boolean(), nullable=True),
        sa.Column('max_tokens', sa.Integer(), nullable=True),
        sa.Column('timeout_seconds', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('agent_type')
    )
    
    # Create agent_configurations table
    op.create_table('agent_configurations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('agent_definition_id', sa.UUID(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=True),
        sa.Column('enabled_by', sa.UUID(), nullable=True),
        sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('custom_name', sa.String(length=100), nullable=True),
        sa.Column('custom_description', sa.Text(), nullable=True),
        sa.Column('custom_settings', sa.JSON(), nullable=True),
        sa.Column('execution_mode_override', sa.Enum('automatic', 'confirmation_required', 'scheduled', name='agentexecutionmode'), nullable=True),
        sa.Column('requires_approval', sa.Boolean(), nullable=True),
        sa.Column('allowed_users', sa.JSON(), nullable=True),
        sa.Column('max_executions_per_day', sa.Integer(), nullable=True),
        sa.Column('max_executions_per_user_per_day', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], ),
        sa.ForeignKeyConstraint(['enabled_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create agent_executions table
    op.create_table('agent_executions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('configuration_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('execution_type', sa.String(length=50), nullable=False),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('output_data', sa.JSON(), nullable=True),
        sa.Column('document_id', sa.UUID(), nullable=True),
        sa.Column('conversation_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('requires_approval', sa.Boolean(), nullable=True),
        sa.Column('approved_by', sa.UUID(), nullable=True),
        sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('approval_notes', sa.Text(), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['configuration_id'], ['agent_configurations.id'], ),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create agent_execution_logs table
    op.create_table('agent_execution_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('execution_id', sa.UUID(), nullable=False),
        sa.Column('log_level', sa.String(length=20), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('log_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_execution_logs')
    op.drop_table('agent_executions')
    op.drop_table('agent_configurations')
    op.drop_table('agent_definitions')
    
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS agentexecutionmode')
    op.execute('DROP TYPE IF EXISTS agenttype')
    # ### end Alembic commands ###