"""add emma heartbeat tables (Phase 6)

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-02-03 10:00:00.000000

Adds tables for the Heartbeat System (Phase 6 of Emma Reactive):
- emma_heartbeat_configs: Per-tenant heartbeat configuration
- emma_proactive_insights: Proactive insights generated by the Heartbeat System
"""
import json

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6g7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


# Default heartbeat configuration
DEFAULT_HEARTBEAT_CONFIG = {
    "enabled": True,
    "run_interval_hours": 4,
    "priority_threshold": 0.6,
    "max_insights_per_day": 5,
    "max_insights_per_hour": 2,
    "min_interval_minutes": 30,
    "quiet_hours_start": "22:00",
    "quiet_hours_end": "08:00",
    "channel_priority": ["in_app", "email", "telegram", "slack"],
    "batch_low_priority": True,
    "digest_hour": 9,
    "contract_expiry_days_warning": 30,
    "enabled_insight_types": [
        "contract_expiration",
        "compliance_alert",
        "risk_alert",
        "anomaly_detected",
        "task_reminder",
    ],
}


def upgrade():
    # ── Phase 6: Heartbeat & Proactive Intelligence ────────────────

    # Heartbeat configuration per tenant
    op.create_table(
        'emma_heartbeat_configs',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', UUID(as_uuid=True), nullable=False, unique=True),
        sa.Column('config', JSONB, nullable=False, server_default=sa.text(f"'{json.dumps(DEFAULT_HEARTBEAT_CONFIG)}'::jsonb")),
        sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('insights_delivered_today', sa.Integer(), server_default='0'),
        sa.Column('last_insight_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    )
    op.create_index('idx_heartbeat_tenant', 'emma_heartbeat_configs', ['tenant_id'])
    op.create_index('idx_heartbeat_next_run', 'emma_heartbeat_configs', ['next_run_at'])

    # Proactive insights generated by the Heartbeat System
    op.create_table(
        'emma_proactive_insights',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('tenant_id', UUID(as_uuid=True), nullable=False),
        sa.Column('insight_type', sa.String(50), nullable=False),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('priority_score', sa.Float(), nullable=False),
        sa.Column('urgency', sa.String(20), server_default="'medium'"),
        sa.Column('confidence', sa.Float(), server_default='0.8'),
        sa.Column('related_documents', JSONB, server_default='[]'),
        sa.Column('suggested_actions', JSONB, server_default='[]'),
        sa.Column('reasoning', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), server_default="'pending'"),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('acted_on_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index('idx_insights_tenant_status', 'emma_proactive_insights', ['tenant_id', 'status'])
    op.create_index('idx_insights_tenant_type', 'emma_proactive_insights', ['tenant_id', 'insight_type'])
    op.create_index('idx_insights_tenant_priority', 'emma_proactive_insights', ['tenant_id', 'priority_score'])
    op.create_index('idx_insights_created', 'emma_proactive_insights', ['created_at'])
    op.create_index('idx_insights_expires', 'emma_proactive_insights', ['expires_at'])


def downgrade():
    op.drop_table('emma_proactive_insights')
    op.drop_table('emma_heartbeat_configs')
