log:
  stdout: true
  level: "info"

persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 1
  datastores:
    default:
      sql:
        pluginName: "postgres12"
        databaseName: "temporalio-nexus"
        connectAddr: "db:5432"
        connectProtocol: "tcp"
        user: "nexus_user"
        password: "nexus_password"
        maxConns: 20
        maxIdleConns: 2
        maxConnLifetime: "1h"
    visibility:
      sql:
        pluginName: "postgres12"
        databaseName: "temporalio-nexus_visibility"
        connectAddr: "db:5432"
        connectProtocol: "tcp"
        user: "nexus_user"
        password: "nexus_password"
        maxConns: 20
        maxIdleConns: 2
        maxConnLifetime: "1h"

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: "127.0.0.1"
  pprof:
    port: 7936
  metrics:
    prometheus:
      timerType: "histogram"
      listenAddress: "0.0.0.0:9090"

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"
      httpPort: 7243
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:9090"

  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:9091"

  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:9092"

  worker:
    rpc:
      grpcPort: 7239
      membershipPort: 6939
      bindOnLocalHost: false
      bindOnIP: "0.0.0.0"
    metrics:
      prometheus:
        timerType: "histogram"
        listenAddress: "0.0.0.0:9093"

clusterMetadata:
   enableGlobalNamespace: false
   failoverVersionIncrement: 10
   masterClusterName: "active"
   currentClusterName: "active"
   clusterInformation:
     active:
       enabled: true
       initialFailoverVersion: 1
       rpcName: "temporal-frontend"
       rpcAddress: "temporalio-server:7233"

dcRedirectionPolicy:
  policy: "noop"

archival:
  history:
    state: "disabled"
    enableRead: false
  visibility:
    state: "disabled"
    enableRead: false

namespaceDefaults:
  archival:
    history:
      state: "disabled"
    visibility:
      state: "disabled"

publicClient:
  hostPort: "temporalio-server:7233"
