"""
Emma ReAct Agent --- Send Email Tool

Allows the ReAct agent to send emails with optional attachments
(generated documents). Uses the SMTP infrastructure already configured
in the deployment.

Security model:
- The LLM can send to ANY address, but only after explicit user confirmation
- The tool has a `confirmed` flag: first call previews, second call sends
- Attachments are limited to documents generated by generate_document tool
- Rate limited to prevent abuse (max 5 emails per conversation)

SMTP configuration is read from environment variables (same as the main
backend email service): MAIL_SERVER, MAIL_PORT, MAIL_USERNAME, etc.
"""

import json
import logging
from email.message import EmailMessage
from typing import Any, Dict, Optional, Type

from pydantic import BaseModel, Field

from .base import EmmaTool, ToolResult

logger = logging.getLogger(__name__)

# Rate limiting per conversation
_MAX_EMAILS_PER_CONVERSATION = 5
GENERATED_DOC_PREFIX = "emma:generated_doc:"


class SendEmailInput(BaseModel):
    """Input for sending an email."""
    to: str = Field(
        description="Direccion de email del destinatario."
    )
    subject: str = Field(
        description="Asunto del email."
    )
    body: str = Field(
        description="Cuerpo del email en texto plano. "
        "Redacta un mensaje profesional y claro."
    )
    attachment_id: Optional[str] = Field(
        default=None,
        description="ID del documento generado para adjuntar (obtenido de generate_document). "
        "Ejemplo: 'gen_abc123def456'."
    )
    confirmed: bool = Field(
        default=False,
        description="IMPORTANTE: Siempre llama primero con confirmed=false para mostrar "
        "un preview al usuario. Solo usa confirmed=true despues de que el usuario "
        "confirme explicitamente que quiere enviar el email."
    )


class SendEmailTool(EmmaTool):
    """Send emails with optional document attachments.

    Two-step flow for user confirmation:
    1. First call (confirmed=false): returns a preview of the email
    2. Second call (confirmed=true): actually sends the email

    This ensures the user always sees and approves the email before sending.
    """

    @property
    def name(self) -> str:
        return "send_email"

    @property
    def description(self) -> str:
        return (
            "Envía email con adjuntos opcionales. "
            "Llama con confirmed=false para preview, confirmed=true solo tras confirmación."
        )

    @property
    def parameters_schema(self) -> Type[BaseModel]:
        return SendEmailInput

    async def execute(self, arguments: Dict[str, Any], context: Dict[str, Any]) -> ToolResult:
        to = arguments["to"]
        subject = arguments["subject"]
        body = arguments["body"]
        attachment_id = arguments.get("attachment_id")
        confirmed = arguments.get("confirmed", False)

        # Basic email validation
        if not to or "@" not in to or "." not in to.split("@")[-1]:
            return ToolResult.from_error(
                f"Direccion de email invalida: '{to}'",
                suggestion="Proporciona una direccion de email valida (ejemplo: usuario@dominio.com).",
            )

        # Rate limiting check
        emails_sent = context.get("emails_sent_count", 0)
        if emails_sent >= _MAX_EMAILS_PER_CONVERSATION:
            return ToolResult.from_error(
                f"Limite de emails alcanzado ({_MAX_EMAILS_PER_CONVERSATION} por conversacion).",
                suggestion="No se pueden enviar mas emails en esta conversacion.",
            )

        # Resolve attachment metadata if provided
        attachment_info = None
        if attachment_id:
            attachment_info = await _get_attachment_info(attachment_id)
            if attachment_info is None:
                return ToolResult.from_error(
                    f"Documento adjunto no encontrado: '{attachment_id}'. "
                    "Puede haber expirado (disponible 1 hora tras generarse).",
                    suggestion="Genera el documento de nuevo con generate_document.",
                )

        # --- Preview mode (confirmed=false) ---
        if not confirmed:
            preview = (
                f"**Preview del email a enviar:**\n\n"
                f"**Para**: {to}\n"
                f"**Asunto**: {subject}\n"
                f"**Cuerpo**:\n{body}\n"
            )
            if attachment_info:
                preview += (
                    f"\n**Adjunto**: {attachment_info['title']} "
                    f"({attachment_info['size_kb']:.1f} KB, DOCX)\n"
                )
            preview += (
                "\n---\n"
                "Pregunta al usuario si confirma el envio de este email. "
                "Si confirma, llama a send_email de nuevo con los mismos parametros "
                "y confirmed=true."
            )
            return ToolResult(
                output=preview,
                data={"preview": True, "to": to},
            )

        # --- Send mode (confirmed=true) ---
        try:
            attachment_bytes = None
            attachment_filename = None
            if attachment_id and attachment_info:
                attachment_bytes = await _get_attachment_bytes(attachment_id)
                if attachment_bytes:
                    # Sanitize filename
                    safe_title = "".join(
                        c if c.isalnum() or c in (" ", "-", "_") else "_"
                        for c in attachment_info.get("title", "documento")
                    ).strip()
                    attachment_filename = f"{safe_title}.docx"

            result = await _send_smtp_email(
                to=to,
                subject=subject,
                body=body,
                attachment_bytes=attachment_bytes,
                attachment_filename=attachment_filename,
            )

            if not result["success"]:
                return ToolResult.from_error(
                    f"Error enviando email: {result.get('error', 'unknown')}",
                    suggestion="Verifica la direccion del destinatario e intenta de nuevo.",
                )

            output = (
                f"Email enviado exitosamente:\n\n"
                f"**Para**: {to}\n"
                f"**Asunto**: {subject}\n"
            )
            if attachment_filename:
                output += f"**Adjunto**: {attachment_filename}\n"
            output += f"\n**Message-ID**: {result.get('message_id', 'N/A')}"

            return ToolResult(
                output=output,
                data={
                    "sent": True,
                    "to": to,
                    "message_id": result.get("message_id"),
                },
            )

        except Exception as e:
            logger.error(f"send_email: unexpected error: {e}", exc_info=True)
            return ToolResult.from_error(
                f"Error inesperado enviando email: {e}",
                suggestion="Intenta de nuevo o verifica la configuracion SMTP.",
            )


async def _get_attachment_info(attachment_id: str) -> Optional[Dict[str, Any]]:
    """Get metadata for a generated document from Redis."""
    try:
        import redis.asyncio as aioredis
        from app.core.config import settings

        r = aioredis.from_url(settings.redis_url)
        meta_raw = await r.get(f"{GENERATED_DOC_PREFIX}{attachment_id}:meta")
        await r.aclose()

        if not meta_raw:
            return None

        meta = json.loads(meta_raw)
        meta["size_kb"] = meta.get("size_bytes", 0) / 1024
        return meta
    except Exception as e:
        logger.error(f"Failed to get attachment info: {e}")
        return None


async def _get_attachment_bytes(attachment_id: str) -> Optional[bytes]:
    """Get DOCX bytes for a generated document from Redis."""
    try:
        import redis.asyncio as aioredis
        from app.core.config import settings

        r = aioredis.from_url(settings.redis_url)
        data = await r.get(f"{GENERATED_DOC_PREFIX}{attachment_id}:bytes")
        await r.aclose()
        return data
    except Exception as e:
        logger.error(f"Failed to get attachment bytes: {e}")
        return None


async def _send_smtp_email(
    to: str,
    subject: str,
    body: str,
    attachment_bytes: Optional[bytes] = None,
    attachment_filename: Optional[str] = None,
) -> Dict[str, Any]:
    """Send an email via SMTP using settings configuration."""
    import aiosmtplib
    from app.core.config import settings

    smtp_host = settings.mail_server
    smtp_port = settings.mail_port
    smtp_user = settings.mail_username
    smtp_pass = settings.mail_password
    from_email = settings.mail_from or smtp_user
    from_name = settings.mail_from_name
    use_ssl = settings.mail_ssl_tls
    use_starttls = settings.mail_starttls

    if not smtp_user or not smtp_pass:
        return {"success": False, "error": "SMTP credentials not configured (MAIL_USERNAME/MAIL_PASSWORD)"}

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = f"{from_name} <{from_email}>"
    msg["To"] = to
    msg.set_content(body)

    # Attach DOCX if provided
    if attachment_bytes and attachment_filename:
        msg.add_attachment(
            attachment_bytes,
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.wordprocessingml.document",
            filename=attachment_filename,
        )

    try:
        if use_ssl:
            await aiosmtplib.send(
                msg,
                hostname=smtp_host,
                port=smtp_port,
                username=smtp_user,
                password=smtp_pass,
                use_tls=True,
            )
        else:
            await aiosmtplib.send(
                msg,
                hostname=smtp_host,
                port=smtp_port,
                username=smtp_user,
                password=smtp_pass,
                start_tls=use_starttls,
            )
        return {"success": True, "message_id": msg["Message-ID"]}
    except Exception as e:
        logger.error(f"SMTP send failed: {e}")
        return {"success": False, "error": str(e)}
