"""
Memory Bank API

Endpoints for storing and querying document memories in the sector graph.
Called by:
- weaviate-service (indexing pipeline) to store memories after document indexing
- emma-agent-service (planner model) to recall memories for retrieval clue generation
"""

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel, Field

from app.core.security import verify_api_key
from app.services.memory_bank_service import memory_bank

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/tree/memory", tags=["memory-bank"])


# ─── Request/Response Models ─────────────────────────────────

class StoreMemoryRequest(BaseModel):
    tenant_id: str
    document_id: str
    summary: str = Field(..., description="Compact document summary (2-3 sentences)")
    key_entities: List[str] = Field(default_factory=list, description="Important entity names")
    key_topics: List[str] = Field(default_factory=list, description="Key topics/themes")
    domain: Optional[str] = Field(None, description="Business domain (legal, fiscal, etc.)")
    semantic_type: Optional[str] = Field(None, description="Document type (factura, contrato, etc.)")


class StoreMemoryResponse(BaseModel):
    success: bool
    document_id: Optional[str] = None
    error: Optional[str] = None


class StoreBulkRequest(BaseModel):
    tenant_id: str
    memories: List[StoreMemoryRequest]


class StoreBulkResponse(BaseModel):
    success: bool
    stored: int = 0
    failed: int = 0
    errors: List[str] = Field(default_factory=list)


class RecallRequest(BaseModel):
    tenant_id: str
    query_topics: Optional[List[str]] = Field(None, description="Topics to match")
    domain: Optional[str] = None
    semantic_type: Optional[str] = None
    limit: int = Field(50, ge=1, le=200)


class MemoryItem(BaseModel):
    document_id: Optional[str] = None
    summary: Optional[str] = None
    key_entities: List[str] = Field(default_factory=list)
    key_topics: List[str] = Field(default_factory=list)
    domain: Optional[str] = None
    semantic_type: Optional[str] = None
    memory_version: Optional[Any] = None
    updated_at: Optional[str] = None


class StatsResponse(BaseModel):
    total_memories: int = 0
    by_domain: Dict[str, int] = Field(default_factory=dict)
    by_type: Dict[str, int] = Field(default_factory=dict)


# ─── Endpoints ────────────────────────────────────────────────

@router.post("/store", response_model=StoreMemoryResponse)
async def store_memory(
    request: StoreMemoryRequest,
    _: bool = Depends(verify_api_key),
):
    """
    Store or update a document memory.

    Called by weaviate-service after document indexing. The memory is
    generated by the planner LLM and contains a compact summary plus
    extracted entities and topics.
    """
    result = await memory_bank.store_memory(
        tenant_id=request.tenant_id,
        document_id=request.document_id,
        summary=request.summary,
        key_entities=request.key_entities,
        key_topics=request.key_topics,
        domain=request.domain,
        semantic_type=request.semantic_type,
    )
    return StoreMemoryResponse(**result)


@router.post("/store/bulk", response_model=StoreBulkResponse)
async def store_memories_bulk(
    request: StoreBulkRequest,
    _: bool = Depends(verify_api_key),
):
    """
    Store multiple document memories in one call.

    Used for batch memory generation during onboarding or backfill.
    """
    stored = 0
    failed = 0
    errors = []

    for mem in request.memories:
        result = await memory_bank.store_memory(
            tenant_id=request.tenant_id,
            document_id=mem.document_id,
            summary=mem.summary,
            key_entities=mem.key_entities,
            key_topics=mem.key_topics,
            domain=mem.domain,
            semantic_type=mem.semantic_type,
        )
        if result.get("success"):
            stored += 1
        else:
            failed += 1
            errors.append(f"{mem.document_id}: {result.get('error', 'unknown')}")

    return StoreBulkResponse(success=True, stored=stored, failed=failed, errors=errors)


@router.post("/recall", response_model=List[MemoryItem])
async def recall_memories(
    request: RecallRequest,
    _: bool = Depends(verify_api_key),
):
    """
    Recall document memories matching given criteria.

    This is the main query interface for the planner model.
    Returns lightweight memory summaries to guide retrieval.
    """
    memories = await memory_bank.recall(
        tenant_id=request.tenant_id,
        query_topics=request.query_topics,
        domain=request.domain,
        semantic_type=request.semantic_type,
        limit=request.limit,
    )
    return [MemoryItem(**m) for m in memories]


@router.get("/{document_id}", response_model=Optional[MemoryItem])
async def get_memory(
    document_id: str,
    tenant_id: str = Query(..., description="Tenant identifier"),
    _: bool = Depends(verify_api_key),
):
    """Get the memory for a specific document."""
    result = await memory_bank.get_memory(tenant_id=tenant_id, document_id=document_id)
    if result is None:
        return None
    return MemoryItem(**result)


@router.get("/", response_model=List[str])
async def list_memorized_documents(
    tenant_id: str = Query(..., description="Tenant identifier"),
    _: bool = Depends(verify_api_key),
):
    """List all document IDs that have memories. Used to skip re-generation."""
    return await memory_bank.get_all_document_ids_with_memory(tenant_id=tenant_id)


@router.delete("/{document_id}")
async def delete_memory(
    document_id: str,
    tenant_id: str = Query(..., description="Tenant identifier"),
    _: bool = Depends(verify_api_key),
):
    """Delete a document's memory."""
    deleted = await memory_bank.delete_memory(tenant_id=tenant_id, document_id=document_id)
    return {"success": deleted, "document_id": document_id}


@router.get("/stats/summary", response_model=StatsResponse)
async def get_stats(
    tenant_id: str = Query(..., description="Tenant identifier"),
    _: bool = Depends(verify_api_key),
):
    """Get memory bank statistics for a tenant."""
    return await memory_bank.get_stats(tenant_id=tenant_id)
