frontend.enableClientVersionCheck:
- value: false

system.enableActivityLocalDispatchByNamespace:
- value: true

system.enableEagerWorkflowStart:
- value: true

history.persistenceMaxQPS:
- value: 3000

frontend.persistenceMaxQPS:
- value: 3000

frontend.throttledLogRPS:
- value: 20

history.defaultWorkflowTaskTimeout:
- value: 10s

frontend.rPS:
- value: 2400

matching.rPS:
- value: 1200

worker.rPS:
- value: 1200