"""
Constants for Emma AI preference learning system.
"""

# User profile limits
MAX_FREQUENT_QUERIES = 50
MAX_FREQUENT_DOCUMENTS = 100
MAX_INTERACTIONS_PER_USER = 1000

# Buffer settings
INTERACTION_BUFFER_THRESHOLD = 10

# Cache TTL (hours)
PROFILE_CACHE_TTL_HOURS = 24

# Redis TTL (seconds)
REDIS_INTERACTION_TTL_SECONDS = 3600 * 24 * 7  # 7 days
REDIS_PROFILE_TTL_SECONDS = 3600 * 24  # 1 day

# Ranking weights (sum should be 1.0)
DEFAULT_RANKING_WEIGHT_RECENCY = 0.3
DEFAULT_RANKING_WEIGHT_FREQUENCY = 0.4
DEFAULT_RANKING_WEIGHT_RELEVANCE = 0.3
MAX_RANKING_WEIGHT = 1.0

# Feedback adjustment
FEEDBACK_WEIGHT_ADJUSTMENT = 0.1
